Completed Prep Javascript Conditionals Exercise - Allyson Greven
allygreven/javascript-prep-0924-code-solutions pull request #9
Opened 2024-10-05 21:32 UTC by allygreven

<img width="1440" alt="Screenshot 2024-10-05 at 2 29 32 PM" src="https://github.com/user-attachments/assets/dab484fa-16eb-4a95-ab92-ae274a3f0277">

2024-10-07 22:43 UTC, robgmerrill requested changes
Couple small changes requested :)

2024-10-07 22:43 UTC, robgmerrill commented on prep-javascript-conditionals/main.js
> +  if (age <= 18) {
Close! 18 would be an adult. So in this case you would want to check if `age < 18` to confirm that they are not an adult.

2024-10-07 22:43 UTC, robgmerrill commented on prep-javascript-conditionals/main.js
> +  if (score <= 70) {
Same as above comment :)

2024-10-07 22:43 UTC, robgmerrill commented on prep-javascript-conditionals/main.js
> +  if (age <= 18) {
or `age <= 17`

2024-10-09 00:40 UTC, allygreven commented
<img width="1440" alt="Screenshot 2024-10-08 at 5 38 53 PM" src="https://github.com/user-attachments/assets/a2e188f0-3683-4f25-ade4-a7d626b43a1d">

2024-10-09 03:16 UTC, allygreven commented
after going over the exercise, I know where I messed up... again. Will fix and resubmit 👍🏼

2024-10-09 16:18 UTC, robgmerrill approved these changes
👍

2024-10-11 03:22 UTC, merged